### ISSUE TITLE
serial number nomenclature

### ISSUE THREAD

**Issue by bitsofinfo** [open205/schema-205#44]
Hi, ended up finding out ASHRAE 205P in an article about interpreting appliance manufacturer serial number plate nomenclatures... and how apparently there might be some effort to get to standardization in this area. Do you guys know of any other software (maybe this) that deals with interpreting the various model/serial number plate nomenclatures out there?

**Comment by nealkruis** [comment]
Each manufacturer has their own convention. It is not the intent of ASHRAE 205 to interpret model numbers outside of determining whether a particular piece of equipment matches the model number pattern provided in a representation.

**Comment by bitsofinfo** [comment]
Thanks @nealkruis, are you aware of any open source or proprietary databases that house all this nomenclature data today?

**Comment by nealkruis** [comment]
I'm not exactly sure what you are looking for, but [AHRI's Directory of Certified Product Performance](https://www.ahridirectory.org/Search/SearchHome) lists most product model numbers. It might be a useful resource.
